New concept
Cromwill/Project-Ball pull request #1
Opened 2020-02-18 15:40 UTC by Cromwill

Create project

2020-02-27 12:47 UTC, HolyMonkey requested changes

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/ActionObjectSpawner.cs
> +    [SerializeField] PhysicsActionScriptableObject[] _physicsActionObjects;
private

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/ActionObjectSpawner.cs
> +    [SerializeField] PhysicsActionScriptableObject[] _physicsActionObjects;
_physicsActions

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/ActionObjectSpawner.cs
> +            _currentAvatar.GetComponent<Transform>().position = anchor.GetPosition();
_currentAvatar имеет смысл сделать типом Transform?

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/ActionObjectSpawner.cs
> +                var v = Instantiate(_currentActionObject.ActionObject);
v?

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/ActionObjects/ActionObjectAnchor.cs
> +    public void ChangeColor()
Toggle

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/ActionObjects/ActionObjectAnchor.cs
> +    private ColorAlpha _colorAlpha = ColorAlpha.Idle;
Это используется?

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/ActionObjects/ActionObjectBase.cs
> +public class ActionObjectBase : PoolObject
Base тут лишнее

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/ActionObjects/ActionObjectBase.cs
> +    }
Почему бы не сделать методы абстрактными которые не имеют реализации?

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/ActionObjects/ActionObjectBase.cs
> +    public void SetPosition(Vector2 position)
Может назвать метод Place?

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/ActionObjects/ActionObjectBase.cs
> +
Для эти методы? Вот тут я бы добавил комментарии что описывают этим методы

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/ActionObjects/ActiveBlock.cs
> +    private float _power;
В одну строку

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/ActionObjects/ActiveBlock.cs
> +    private void SpeedControl()
ГлаголСуществительное

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/ActionObjects/AnchorController.cs
> +    }
Мусор?

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/ActionObjects/Propeller.cs
> +    }
Зачем метод Work в базовом классе если наследники сами его вызывают?

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/MouseControl.cs
> +public class MouseControl : MonoBehaviour
Имя не отражает суть

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/ObjectMove.cs
> +
Нужно существительное

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/SpawnAndObjectPool/ObjectsPoolForBalls.cs
> +public class ObjectsPoolForBalls : ObjectsPool<Ball>
BallsPool

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/SpawnAndObjectPool/ObjectsPoolForBalls.cs
> +
Лишняя строка

2020-02-27 12:47 UTC, HolyMonkey commented on Assets/Scriptes/Ball_2/UI/ActionObjectShopButton.cs
> +    public static event Action<PhysicsActionScriptableObject> UsingActionObject;
Нам бы хотелось отказаться от статических событий

2020-02-27 14:16 UTC, Cromwill commented on Assets/Scriptes/Ball_2/ActionObjectSpawner.cs
> +            _currentAvatar.GetComponent<Transform>().position = anchor.GetPosition();
нет, он отображается на экране.

2020-02-27 15:00 UTC, Cromwill commented on Assets/Scriptes/Ball_2/ActionObjectSpawner.cs
> +    [SerializeField] PhysicsActionScriptableObject[] _physicsActionObjects;
+

2020-02-27 17:14 UTC, Cromwill commented on Assets/Scriptes/Ball_2/ActionObjectSpawner.cs
> +    [SerializeField] PhysicsActionScriptableObject[] _physicsActionObjects;
Поле удалено

2020-02-27 17:15 UTC, Cromwill commented on Assets/Scriptes/Ball_2/ActionObjectSpawner.cs
> +                var v = Instantiate(_currentActionObject.ActionObject);
Исправлено

2020-02-27 17:15 UTC, Cromwill commented on Assets/Scriptes/Ball_2/ActionObjects/ActionObjectAnchor.cs
> +    public void ChangeColor()
Исправлено

2020-02-27 17:18 UTC, Cromwill commented on Assets/Scriptes/Ball_2/ActionObjects/ActionObjectAnchor.cs
> +    private ColorAlpha _colorAlpha = ColorAlpha.Idle;
_colorAlpha удалил.

2020-02-27 17:18 UTC, Cromwill commented on Assets/Scriptes/Ball_2/ActionObjects/ActionObjectBase.cs
> +public class ActionObjectBase : PoolObject
Удалил приставку Base со всех классов где она была

2020-02-27 17:20 UTC, Cromwill commented on Assets/Scriptes/Ball_2/ActionObjects/ActiveBlock.cs
> +    private float _power;
Класс удален

2020-02-27 17:21 UTC, Cromwill commented on Assets/Scriptes/Ball_2/ActionObjects/ActiveBlock.cs
> +    private void SpeedControl()
Класс удален. Похожий метод в классе Ball переименован

2020-02-27 17:21 UTC, Cromwill commented on Assets/Scriptes/Ball_2/ActionObjects/AnchorController.cs
> +    }
Мусор. Удалено.

2020-02-27 17:26 UTC, Cromwill commented on Assets/Scriptes/Ball_2/MouseControl.cs
> +public class MouseControl : MonoBehaviour
Проблемы с именованием. В данный момент он называется MoverAroundLocation

2020-02-27 17:26 UTC, Cromwill commented on Assets/Scriptes/Ball_2/ObjectMove.cs
> +
В данный момент он называется MoverAroundLocation

2020-02-27 17:27 UTC, Cromwill commented on Assets/Scriptes/Ball_2/SpawnAndObjectPool/ObjectsPoolForBalls.cs
> +public class ObjectsPoolForBalls : ObjectsPool<Ball>
Класс удален за ненадобностью

2020-02-27 17:27 UTC, Cromwill commented on Assets/Scriptes/Ball_2/SpawnAndObjectPool/ObjectsPoolForBalls.cs
> +
Класс удален за ненадобностью

2020-02-27 17:54 UTC, Cromwill commented on Assets/Scriptes/Ball_2/ActionObjects/Propeller.cs
> +    }
Убрал

2020-02-27 18:45 UTC, Cromwill commented on Assets/Scriptes/Ball_2/ActionObjects/ActionObjectBase.cs
> +    }
Методы удалены до появления необходимости в них

2020-02-27 18:45 UTC, Cromwill commented on Assets/Scriptes/Ball_2/ActionObjects/ActionObjectBase.cs
> +
Методы удалены до появления необходимости в них

2020-02-28 10:16 UTC, HolyMonkey requested changes

2020-02-28 10:16 UTC, HolyMonkey commented on Assets/Scriptes/ActionObjectSpawner.cs
> +    public bool IsUsing { get; private set; }
Следует из _currentActionObject

2020-02-28 10:16 UTC, HolyMonkey commented on Assets/Scriptes/ActionObjectSpawner.cs
> +    private bool _currenObjectIsAction => _currentActionObject.GetType == ActionObjectScriptableObject.ActionObjectType.ActionObject ? true : false;
Обьединяется в одном типе

2020-02-28 10:16 UTC, HolyMonkey commented on Assets/Scriptes/ActionObjectSpawner.cs
> +        }
Замени на LINQ

2020-02-28 10:16 UTC, HolyMonkey commented on Assets/Scriptes/ActionObjectSpawner.cs
> +                _currentAnchor = anchors[i];
Анчор хранит ссылку на аватар

2020-02-28 10:16 UTC, HolyMonkey commented on Assets/Scriptes/ActionObjectSpawner.cs
> +                }
Дублях кода

2020-02-28 10:16 UTC, HolyMonkey commented on Assets/Scriptes/ActionObjectSpawner.cs
> +    private void AnchorsChangeState()
AnchorsToggleState

2020-02-28 10:16 UTC, HolyMonkey commented on Assets/Scriptes/ActionObjectSpawner.cs
> +    private void AnchorsChangeState()
ToggleAnchors

2020-02-28 10:16 UTC, HolyMonkey commented on Assets/Scriptes/ActionObjects/ActionObject.cs
> +            _selfTransform = GetComponent<Transform>();
Трансформ на данный момент нет смысла кешировать

2020-02-28 10:16 UTC, HolyMonkey commented on Assets/Scriptes/ActionObjects/AnchorController.cs
> +    }
Мусор

2020-02-28 10:16 UTC, HolyMonkey commented on Assets/Scriptes/MouseControl.cs
> +        var v = Physics2D.OverlapCircle(inputPosition, 0.1f);
v?

2020-02-28 10:16 UTC, HolyMonkey commented on Assets/Scriptes/MouseControl.cs
> +public class MouseControl : MonoBehaviour
Control?

2020-02-28 12:33 UTC, Cromwill commented on Assets/Scriptes/ActionObjects/AnchorController.cs
> +    }
Класс удален

2020-02-29 08:29 UTC, Cromwill commented on Assets/Scriptes/MouseControl.cs
> +public class MouseControl : MonoBehaviour
Заменено на MouseInput

2020-02-29 08:30 UTC, Cromwill commented on Assets/Scriptes/MouseControl.cs
> +        var v = Physics2D.OverlapCircle(inputPosition, 0.1f);
Заменено на hit

2020-02-29 08:49 UTC, Cromwill commented on Assets/Scriptes/ActionObjects/ActionObject.cs
> +            _selfTransform = GetComponent<Transform>();
Перенес кэширование в OnEnable()

2020-02-29 08:51 UTC, Cromwill commented on Assets/Scriptes/ActionObjectSpawner.cs
> +    private void AnchorsChangeState()
Исправил

2020-02-29 15:51 UTC, Cromwill commented on Assets/Scriptes/Ball_2/MouseControl.cs
> +public class MouseControl : MonoBehaviour
Заменено на MouseInput

2020-02-29 15:52 UTC, Cromwill commented on Assets/Scriptes/ActionObjectSpawner.cs
> +    public bool IsUsing { get; private set; }
MouseInput кидает рейкаст если IsUsing.

2020-02-29 15:54 UTC, Cromwill commented on Assets/Scriptes/ActionObjectSpawner.cs
> +    private bool _currenObjectIsAction => _currentActionObject.GetType == ActionObjectScriptableObject.ActionObjectType.ActionObject ? true : false;
Объединил _currentActionObject, _currentAnchor и _currentAvatar в отдельном классе. Вынес логику взаимодействия в этот класс

2020-02-29 15:55 UTC, Cromwill commented on Assets/Scriptes/ActionObjectSpawner.cs
> +        }
Заменил

2020-03-02 11:01 UTC, merged